spring.application.name=ibmapp

spring.datasource.url=jdbc:h2:mem:ibmapp
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

hf.api.token=${HF_API_TOKEN}